### ISSUE TITLE
Forcibly closes every time I delete or move an entry in my library.

### ISSUE THREAD

**Issue by lalalasupa0** [null2264/yokai#51]
### Steps to reproduce

Delete or move an entry

### Expected behavior

It does it, but...

### Actual behavior

...
The app is forcefully closed at the same time

### Crash logs

The app doesn't give me one

### Yōkai version

1.7.14

### Android version

Android 12

### Device

Samsung 10+

### Other details

Might be an issue of my device, however, It is not a heating or battery optimization problem

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.7.14](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by lalalasupa0** [comment]
![Screenshot_20240529_161220_Ykai](https://github.com/null2264/yokai/assets/101371218/b6ee6f3a-6af0-4ae7-b175-18214981bda0)
[yokai_crash_logs.txt](https://github.com/null2264/yokai/files/15491359/yokai_crash_logs.txt)
Screenshot and crash log

**Comment by null2264** [comment]
Seems to caused by outdated database handler, can't be fixed until I modernized the database handler.

**Comment by null2264** [comment]
Probably fixed by https://github.com/null2264/yokai/commit/b17578365d292d6d32f4dba9968859539eba02ad, or at least partially...

**Comment by null2264** [comment]
> ![Screenshot_20240529_161220_Ykai](https://private-user-images.githubusercontent.com/101371218/334981039-b6ee6f3a-6af0-4ae7-b175-18214981bda0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1ODkxMjQsIm5iZiI6MTcxODU4ODgyNCwicGF0aCI6Ii8xMDEzNzEyMTgvMzM0OTgxMDM5LWI2ZWU2ZjNhLTZhZjAtNGFlNy1iMTc1LTE4MjE0OTgxYmRhMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QwMTQ3MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YmJjZjU0MjZkZmFiMWIwNTliODY2MDhiYzhkNTgxYzY5MGE5MDM1YjIwYzY3MTIxYTA4NTU2MDIzMjNlMGY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LnaIutsT9UQyzLxRy9I1YZ_bXNSj14fUi_5xCI8XrNg) [yokai_crash_logs.txt](https://github.com/null2264/yokai/files/15491359/yokai_crash_logs.txt) Screenshot and crash log

This crash is definitely fixed, but I detected other similar crash.

**Comment by lalalasupa0** [comment]
@null2264 
It started crashing in this r5373 update while reading

![Screenshot_20240625_152448_Ykai Nightly](https://github.com/null2264/yokai/assets/101371218/37a228aa-1e09-4cf1-a6e6-bd1ca4d591cb)
[yokai_crash_logs.txt](https://github.com/user-attachments/files/15979449/yokai_crash_logs.txt)

**Comment by null2264** [comment]
That's compose stuff, can't fix it, Google need to fix it unfortunately.

**Comment by lalalasupa0** [comment]
> That's compose stuff, can't fix it, Google need to fix it unfortunately.

When you say Google has to fix it, it really dashes my hopes

You believe it could fix itself in future updates?

**Comment by null2264** [comment]
Interesting, I'll try upgrading compose to newest snapshot and see if that helps, they did say they fixed it, but hasn't release it

**Comment by null2264** [comment]
> > That's compose stuff, can't fix it, Google need to fix it unfortunately.
> 
> When you say Google has to fix it, it dashes my hopes You believe it could fix itself in future updates?
> 
> I also saw a lot of stuff regarding that compose thing in a google search, and this started happening with the new Yokai update only, maybe there is something in it idk
> 
> It's happening a loooooot, really, **a looooooooooooot**

That has been resolved by Google on new beta release (https://github.com/null2264/yokai/commit/2471f454f8fd5e32014893cb9b8c38eb71060016)

REF: https://developer.android.com/jetpack/androidx/releases/compose-ui#1.7.0-beta04

**Comment by lalalasupa0** [comment]
> Interesting, I'll try upgrading compose to newest snapshot and see if that helps, they did say they fixed it, but hasn't release it

It seems that it was fixed with that update (im not completely sure), I forgot to confirm it at the moment

**Comment by null2264** [comment]
Oh, nice.

**Comment by lalalasupa0** [comment]
This is still happening quite a lot btw, more specifically when you enter a manga, remove it, go back to the library, and do the same with other manga (this without stopping)

**Comment by null2264** [comment]
Oh I forgot to give an update here, check out "Other details" on GH-101. Seems to connected to how Android handle database, can't be fixed at the moment unfortunately.
